name: Haskell CI
on: [push]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - name: Build with Nix
      run: nix-build
    - name: Test
      run: nix-shell --run "cabal test"
